package pe.edu.pucp.fasticket.model.notificaciones;

public enum TipoPlantilla {
	CAMBIO_CONTRASENA,
	VERIFICAR_CUENTA,
	CONFIRMACION_COMPRA,
	RECORDATORIO_EVENTO_48H,
	TRANSFERENCIA_OK,
	TRANSFERENCIA_FALLIDA,
	CONFIRMACION_RECUPERACION_CONTRASENA,
	OLVIDO_CONTRASENA_CODIGO
}


